# GHCR镜像验证环境 Override
# 配合基座使用：docker compose -f docker-compose.yml -f docker-compose.ghcr.yml up

services:
  app:
    # 使用GHCR镜像而非本地构建
    image: ghcr.io/haizhouyuan/storyapp:${APP_TAG:-latest}
    container_name: storyapp-ghcr
    
    # 生产环境变量
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - ENABLE_DETAILED_LOGGING=false
      - LOG_LEVEL=info
    
    # GHCR验证端口映射 - 避免与dev环境冲突
    ports:
      - "5002:5000"  # 外部5002映射到容器5000
  
  mongo:
    # GHCR验证数据库配置
    environment:
      MONGO_INITDB_DATABASE: storyapp_ghcr
    # 不暴露端口，增强安全性
    # ports: []
