# 优化的Docker Compose配置
# 支持构建缓存、资源限制和监控

version: '3.8'

services:
  # MongoDB数据库服务
  mongo:
    image: mongo:6.0
    container_name: storyapp-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-pass123}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-storyapp}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - storyapp-network
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_USER:-root}", "--password", "${MONGO_PASS:-pass123}", "--authenticationDatabase", "admin", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:20-alpine}
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmmirror.com}
      # 启用BuildKit缓存
      cache_from:
        - storyapp:latest
        - storyapp:builder
      target: production
    image: storyapp:latest
    container_name: storyapp-backend
    restart: unless-stopped
    environment:
      # 应用配置
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      
      # 数据库配置
      MONGODB_URI: mongodb://${MONGO_USER:-root}:${MONGO_PASS:-pass123}@mongo:27017/${MONGO_DB:-storyapp}?authSource=admin
      MONGODB_DB_NAME: ${MONGO_DB:-storyapp}
      
      # API配置
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK_API_URL: ${DEEPSEEK_API_URL:-https://api.deepseek.com}
      
      # 前端配置
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      
      # 日志配置
      ENABLE_DETAILED_LOGGING: ${ENABLE_DETAILED_LOGGING:-true}
      ENABLE_DB_LOGGING: ${ENABLE_DB_LOGGING:-true}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_RETENTION_DAYS: ${LOG_RETENTION_DAYS:-30}
      
      # 性能配置
      NODE_OPTIONS: "--max-old-space-size=1024"
    ports:
      - "${APP_PORT:-5001}:5000"
    volumes:
      # 数据持久化
      - app_logs:/app/logs
      - app_uploads:/app/uploads
    networks:
      - storyapp-network
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:5000/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  # 可选：Nginx反向代理（生产环境推荐）
  nginx:
    image: nginx:alpine
    container_name: storyapp-nginx
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - nginx_logs:/var/log/nginx
      # SSL证书挂载点（如果启用HTTPS）
      # - ./certs:/etc/nginx/certs:ro
    networks:
      - storyapp-network
    depends_on:
      - app
    profiles:
      - nginx
      - production
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

networks:
  storyapp-network:
    driver: bridge
    name: storyapp-network

volumes:
  # 数据库数据持久化
  mongo_data:
    name: storyapp-mongo-data
  mongo_config:
    name: storyapp-mongo-config
  
  # 应用数据持久化
  app_logs:
    name: storyapp-logs
  app_uploads:
    name: storyapp-uploads
  
  # Nginx日志
  nginx_logs:
    name: storyapp-nginx-logs

# 扩展配置示例
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-resource-limits: &default-limits
  limits:
    memory: 512M
    cpus: '0.5'
  reservations:
    memory: 256M
    cpus: '0.25'