# 开发环境 Override - 源码挂载 + 热更新
# 配合基座使用：docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    # 本地构建，不依赖GHCR
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:18-alpine}
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmmirror.com}
    image: storyapp:dev
    container_name: storyapp-dev
    
    # 开发环境变量
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
      - ENABLE_DETAILED_LOGGING=true
      - LOG_LEVEL=debug
    
    # 热更新模式 - 挂载源码
    command: ["npm", "run", "dev"]  # 需要后端package.json中有dev脚本
    volumes:
      # 挂载源码目录实现热更新
      - ./backend:/app/backend
      - ./shared:/app/shared
      - ./frontend/build:/app/backend/dist/public  # 前端构建结果
      # 保护node_modules不被覆盖
      - /app/node_modules
      - /app/backend/node_modules
      - /app/shared/node_modules
    
    # 开发端口映射
    ports:
      - "5000:5000"  # 直接映射，便于本地调试
    
    # 开发环境不暴露数据库端口（安全考虑）
  
  mongo:
    # 开发数据库配置
    environment:
      MONGO_INITDB_DATABASE: storyapp_dev
    # 暴露端口便于本地工具连接
    ports:
      - "27017:27017"