# CI测试环境配置
# 用于GitHub Actions中的容器化测试

name: storyapp

services:
  # MongoDB测试数据库
  mongo:
    image: mongo:6.0
    container_name: storyapp-mongo-ci
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: storyapp
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"]
      interval: 15s
      timeout: 5s
      retries: 12

  # 应用测试服务
  app:
    build: .
    container_name: storyapp-app-ci
    environment:
      - DEEPSEEK_API_KEY=sk-test-dummy
      - DEEPSEEK_API_URL=https://api.deepseek.com
      - MONGODB_URI=mongodb://root:pass123@mongo:27017/storyapp?authSource=admin
      - NODE_ENV=test
      - PORT=5000
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:5000/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\""]
      interval: 15s
      timeout: 5s
      retries: 10