#!/bin/bash

# 清洁的阿里云服务器SSH密钥设置指南
# 确保在正确的服务器环境中执行

echo "🔧 阿里云服务器SSH密钥设置指南"
echo "==============================="
echo ""
echo "⚠️  重要提醒："
echo "请确保你在正确的阿里云服务器终端中执行以下命令"
echo "服务器主机名应该是：iZf8z3uu2ea9wt48g6j5yoZ"
echo "服务器IP应该包含：47.120.74.212"
echo ""

echo "📋 步骤1：验证服务器身份"
echo "------------------------"
echo "# 执行以下命令确认你在正确的服务器上："
echo "echo '=== 服务器身份验证 ==='"
echo "echo '主机名:' && hostname"
echo "echo 'IP地址:' && ip addr show | grep 'inet ' | grep -v '127.0.0.1'"
echo "echo '当前用户:' && whoami"
echo "echo '当前路径:' && pwd"
echo ""
echo "期望结果："
echo "- 主机名: iZf8z3uu2ea9wt48g6j5yoZ"
echo "- IP地址: 应包含 47.120.74.212"
echo "- 用户: root"
echo "- 路径: /root"
echo ""

echo "📋 步骤2：设置SSH密钥（仅在验证通过后执行）"
echo "-------------------------------------------"
echo ""
echo "# 如果步骤1验证通过，再执行以下命令："
echo ""
echo "# 备份现有配置"
echo "cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true"
echo ""
echo "# 创建SSH目录"
echo "mkdir -p ~/.ssh"
echo "chmod 700 ~/.ssh"
echo ""
echo "# 清理并设置authorized_keys"
echo "cat > ~/.ssh/authorized_keys << 'SSHKEY_EOF'"
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCTnNkbs+K/3SoOix5KCBiNL9hUGLkFOkRBeMVtangyDVvsu8FTfallIPBbz6J42yTfXEfv38/H/9XqMvPI/Z3NVYfpp+t+KusxjyzguP6cTovLpdslwRcsl/Ehte3YlJlZJs4LGCSPkcfh+A/bkAVyK+E1NE9QPIvR488co3thPsFaONUtOLGF0yrqe1L5XJlax2XajDbIe+Z9oQsZ3sJsmU48j7Ji0T9ba70pk88gqYfrU+vztOuqg8/tdLxElfWOwJ44LUp2iYr3+YblKNnpYFDUNfxHjEET2FlYv1yjjzPSVfnmbVUi3Vi1jbQrKk2PoRIG/nzDnulMI3SfIkzrksPjsL2ZNdVoem6hKs/aWAQSuZN8ik+y8SiDsiBbFXhJenfCTHS0s5bNssLVIJnTBE0BWfeRKm3dWpbbBr7EOMRdmlfeKHGQCVp5fl4Q9aWGGPLBGb2T3X0eHNlEGZ4mY05K/km1d3zIW3pycyoqgB5Njo+BlA5gyEp96AZ3f/4TZZPnExeNTadGmxBJEqlqMNJYUquH/3UHIy+oNtwsiYnXgJEsTugfpXFACey39yUf0cbsbS0ys9sydthGqAWyzEJmlIOBOmsYkA5Fxo4kxKS8pZGNrIcmfqxM9jqx3X4EDGMkJy5qskFqDngcrUX4OvH/qH9oJqnPFoV4P2paCw== storyapp-20250922"
echo "SSHKEY_EOF"
echo ""
echo "# 设置权限"
echo "chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "# 验证设置"
echo "echo '=== 验证SSH设置 ==='"
echo "echo 'SSH目录权限:'"
echo "ls -la ~/.ssh/"
echo "echo ''"
echo "echo 'authorized_keys内容检查:'"
echo "wc -l ~/.ssh/authorized_keys"
echo "head -c 50 ~/.ssh/authorized_keys && echo '...'"
echo ""

echo "📋 步骤3：最终验证"
echo "-----------------"
echo "echo '=== 最终验证 ==='"
echo "echo '服务器信息:'"
echo "hostname && hostname -I"
echo "echo 'SSH配置完成，可以退出服务器测试连接'"
echo ""

echo "🧪 本地测试命令"
echo "==============="
echo "# 在本地机器上执行："
echo "ssh -o BatchMode=yes -o ConnectTimeout=10 storyapp-server 'echo \"SSH免密登录成功 - \$(date)\"'"
