name: Debug Claude API Connection

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  debug-api:
    runs-on: ubuntu-latest
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test API Endpoint
        run: |
          echo "Testing API endpoint connectivity..."
          
          # Test if the base URL is accessible
          BASE_URL="${{ secrets.ANTHROPIC_BASE_URL }}"
          echo "Base URL (masked): ${BASE_URL:0:20}..."
          
          # Test basic connectivity (without auth)
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" "$BASE_URL" || echo "Connection failed"
          
          # Test with API key
          API_KEY="${{ secrets.CLAUDE_API_KEY }}"
          echo "API Key length: ${#API_KEY}"
          echo "API Key prefix: ${API_KEY:0:10}..."
          
          # Test different authentication methods
          echo "Testing x-api-key auth:"
          curl -s \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d '{"model": "claude-3-5-sonnet-20241022", "max_tokens": 10, "messages": [{"role": "user", "content": "Hi"}]}' \
            "$BASE_URL/v1/messages" \
            -w "HTTP Status: %{http_code}\n" || echo "x-api-key auth failed"
          
          echo "Testing Authorization Bearer auth:"
          curl -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $API_KEY" \
            -d '{"model": "claude-3-5-sonnet-20241022", "max_tokens": 10, "messages": [{"role": "user", "content": "Hi"}]}' \
            "$BASE_URL/v1/messages" \
            -w "HTTP Status: %{http_code}\n" || echo "Bearer auth failed"
          
          echo "Testing Authorization with x-api-key prefix:"
          curl -s \
            -H "Content-Type: application/json" \
            -H "Authorization: $API_KEY" \
            -d '{"model": "claude-3-5-sonnet-20241022", "max_tokens": 10, "messages": [{"role": "user", "content": "Hi"}]}' \
            "$BASE_URL/v1/messages" \
            -w "HTTP Status: %{http_code}\n" || echo "Direct auth failed"

      - name: Test Claude Code with Minimal Settings
        uses: anthropics/claude-code-action@v1
        with:
          prompt: "Test connection"
