name: Simple Claude Test

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  contents: read
  id-token: write        # Required for OIDC authentication
  pull-requests: write
  issues: write

jobs:
  claude-test:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    env:                   # ← Job级环境变量，确保子进程都能继承
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assert Anthropic envs
        run: |
          test -n "$ANTHROPIC_API_KEY" || (echo "❌ Missing ANTHROPIC_API_KEY" && exit 1)
          echo "✅ ANTHROPIC_API_KEY present"
          echo "ℹ️ BASE_URL: ${ANTHROPIC_BASE_URL:+set}${ANTHROPIC_BASE_URL:-not-set}"

      - name: Pre-approve custom API key (GAC only)
        if: env.ANTHROPIC_BASE_URL != ''
        run: |
          (cat ~/.claude.json 2>/dev/null || echo 'null') \
            | jq --arg key "${ANTHROPIC_API_KEY: -20}" \
                 '(. // {}) | .customApiKeyResponses.approved |= ([.[]?, $key] | unique)' \
            > ~/.claude.json.tmp && mv ~/.claude.json.tmp ~/.claude.json

      - name: Write Claude settings with API key
        run: |
          mkdir -p ~/.claude
          # 使用printf确保正确的变量替换
          printf '{
            "api_keys": {
              "anthropic": "%s"
            },
            "anthropic": {
              "base_url": "%s"
            },
            "enableAllProjectMcpServers": true
          }\n' "$ANTHROPIC_API_KEY" "$ANTHROPIC_BASE_URL" > ~/.claude/settings.json
          echo "Settings file created:"
          cat ~/.claude/settings.json
        shell: bash
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}

      - name: Test Claude Code
        uses: anthropics/claude-code-action@v1
        # Job级env已经包含所有必要的环境变量，不需要重复配置
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Hello! This is a simple connection test for Claude Code on GitHub Actions.
            
            Please:
            1. Confirm you can connect successfully
            2. Analyze the current project structure briefly  
            3. Provide a short status report
            
            Project context: This is a children's story app with React frontend and Node.js backend.
            
            Keep the response concise and helpful.
