name: Codex Code Fix

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  codex-fix:
    if: contains(github.event.comment.body, '@codex')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          if [ -d "backend" ]; then cd backend && npm install && cd ..; fi
          if [ -d "frontend" ]; then cd frontend && npm install --legacy-peer-deps && cd ..; fi

      - name: Codex Code Fix with Claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}