name: Deploy to Staging (repository-dispatch)

on:
  repository_dispatch:
    types: [staging-deploy]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging via repo dispatch
        uses: ./.github/actions/staging-deploy
        with:
          branch: ${{ github.event.client_payload.branch || 'master' }}
          sha:    ${{ github.event.client_payload.sha || '' }}
        env:
          GHCR_PAT:            ${{ secrets.GHCR_PAT }}
          STAGING_HOST:        ${{ secrets.STAGING_HOST }}
          STAGING_USER:        ${{ secrets.STAGING_USER }}
          STAGING_SSH_KEY:     ${{ secrets.STAGING_SSH_KEY }}
          STAGING_BASE_URL:    ${{ secrets.STAGING_BASE_URL }}
          STAGING_MONGO_URI:   ${{ secrets.STAGING_MONGO_URI }}
          STAGING_DEEPSEEK_API_KEY: ${{ secrets.STAGING_DEEPSEEK_API_KEY }}
