name: Deploy to Staging (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'master'
      sha:
        description: 'Optional commit SHA'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/staging-deploy.reusable.yml
   with:
      branch: ${{ github.event.inputs.branch != '' && github.event.inputs.branch || 'master' }}
      sha:    ${{ github.event.inputs.sha }}
      pr_number: ''
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      STAGING_HOST: ${{ secrets.STAGING_HOST }}
      STAGING_USER: ${{ secrets.STAGING_USER }}
      STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      STAGING_DEEPSEEK_API_KEY: ${{ secrets.STAGING_DEEPSEEK_API_KEY }}
      STAGING_MONGO_URI: ${{ secrets.STAGING_MONGO_URI }}
