name: Deploy to Staging (repo-dispatch)

on:
  repository_dispatch:
    types: [staging-deploy]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/staging-deploy.reusable.yml
    with:
      branch: ${{ github.event.client_payload.branch || 'master' }}
      sha:    ${{ github.event.client_payload.sha || '' }}
      pr_number: ${{ github.event.client_payload.pr_number || '' }}
    secrets:
      GHCR_PAT:        ${{ secrets.GHCR_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      STAGING_HOST:    ${{ secrets.STAGING_HOST }}
      STAGING_USER:    ${{ secrets.STAGING_USER }}
      STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      STAGING_DEEPSEEK_API_KEY: ${{ secrets.STAGING_DEEPSEEK_API_KEY }}
      STAGING_MONGO_URI: ${{ secrets.STAGING_MONGO_URI }}
