name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to staging'
        required: false
        default: 'master'
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event=${{ github.event_name }} branch=${{ github.ref_name }} input=${{ github.event.inputs.branch }}"
