name: Deploy to Staging (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: false
        default: master
      sha:
        description: Optional commit SHA
        required: false

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: staging-${{ inputs.sha != '' && inputs.sha || inputs.branch }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha != '' && inputs.sha || inputs.branch }}

      - name: Deploy to staging
        uses: ./.github/actions/staging-deploy
        with:
          branch: ${{ inputs.branch }}
          sha:    ${{ inputs.sha }}
        env:
          GHCR_PAT:            ${{ secrets.GHCR_PAT }}
          STAGING_HOST:        ${{ secrets.STAGING_HOST }}
          STAGING_USER:        ${{ secrets.STAGING_USER }}
          STAGING_SSH_KEY:     ${{ secrets.STAGING_SSH_KEY }}
          STAGING_BASE_URL:    ${{ secrets.STAGING_BASE_URL }}
          STAGING_MONGO_URI:   ${{ secrets.STAGING_MONGO_URI }}
          STAGING_DEEPSEEK_API_KEY: ${{ secrets.STAGING_DEEPSEEK_API_KEY }}
